# usage: source env_options.sh

export SAMGRAPH_LOG_LEVEL=info
export SAMGRAPH_LOG_HIDE_TIME=1

export SAMGRAPH_PROFILE_LEVEL=3

export SAMGRAPH_REPORT_STEP=OFF
export SAMGRAPH_LOG_NODE_ACCESS=OFF
export SAMGRAPH_SANITY_CHECK=OFF
export SAMGRAPH_PROFILE_CUDA=OFF