#ifndef SAMGRAPH_CONFIG_H
#define SAMGRAPH_CONFIG_H

#define SAMGRAPH_META_FILE "meta.txt"
#define SAMGRAPH_FEAT_FILE "feat.bin"
#define SAMGRAPH_LABEL_FILE "label.bin"
#define SAMGRAPH_INDPTR_FILE "indptr.bin"
#define SAMGRAPH_INDICE_FILE "indice.bin"
#define SAMGRAPH_TRAIN_SET_FILE "train_set.bin"
#define SAMGRAPH_TEST_SET_FILE "test_set.bin"
#define SAMGRAPH_VALID_SET_FILE "valid_set.bin"

#define SAMGRAPH_META_NUM_NODE "NUM_NODE"
#define SAMGRAPH_META_NUM_EDGE "NUM_EDGE"
#define SAMGRAPH_META_FEAT_DIM "FEAT_DIM"
#define SAMGRAPH_META_NUM_CLASS "NUM_CLASS"
#define SAMGRAPH_META_NUM_TRAIN_SET "NUM_TRAIN_SET"
#define SAMGRAPH_META_NUM_TEST_SET "NUM_TEST_SET"
#define SAMGRAPH_META_NUM_VALID_SET "NUM_VALID_SET"

#endif // SAMGRAPH_CONFIG_H
